server:
  port: 8082
spring:
  application:
    name: service-hotline
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    lease-renewal-interval-in-seconds: 3
